- name: 'Disable screen shut down'
  lineinfile:
    dest: "/home/{{ user }}/.config/lxsession/LXDE/autostart"
    line: "{{ item }}"
  with_items:
    - "@xset s off"
    - "@xset -dpms"
    - "@xset s noblank"
  tags:
    - screen

- name: 'Comment screensaver'
  replace:
    dest: "/home/{{ user }}/.config/lxsession/LXDE/autostart"
    regexp: "@xscreensaver -no-splash"
    replace: "#@xscreensaver -no-splah"
  tags:
    - screen