#!/usr/bin/env ansible-playbook

---
- hosts: localhost
  remote_user: root

  roles:
    - role: autostart
      become: true
      become_user: pi
      tags: 
        - autostart

    - role: screen-blank
      become_user: pi
      become: true
      tags:
        - screen

    - role: shutdown-cron
      become_user: root
      become: true
      tags: 
        - shutdown-cron