#!/usr/bin/env ansible-playbook

---
- hosts: localhost
  remote_user: root

  roles:
    - role: autostart
      become: true
      become_user: pi
      tags: 
        - autostart

    - role: configuration
      become_user: pi
      become: true
      tags:
        - configuration
