- name: "Install chrome"
  apt:
    name: chromium-browser
    update_cache: true
    install_recommends: yes
    state: present
    force: true
  become_user: root
  become: true

- name: "Add chrome autostart as new line in LXDE autostart file"
  lineinfile:
    dest: "/home/{{ user }}/.config/lxsession/LXDE/autostart"
    line: "{{ item }}"
  with_items:
      - "@chromium-browser --incognito --kiosk {{ href }}"
  tags:
    - chrome-autostart
